### ISSUE TITLE
Error creación Base de Datos (pasos 12-13)

### ISSUE THREAD

**Issue by AndrewVenegas** [IIC2143/Setup-Guides#10]
Hola! Tengo un problema al tratar de crear la base de datos. Hice exactamente lo que sale en el paso 11 y 12, pero la base de datos no se crea, y ya en el paso 13 obviamente no logro nada.

El error es el siguiente:
![image](https://user-images.githubusercontent.com/105684850/224399076-e45a918b-1c22-4ea5-9146-bcb74bf92eb2.png)

También probé con el comando "bin/rails db:create" pero no me sirvió. Y traté de buscar en otros lugares, pero no pude resolverlo. 

Les agradecería mucho si me pudieran ayudar :D

**Comment by KainaBGR** [comment]
Hola :) a mi también me pasó. Al parecer el servidor se cae y hay que reiniciarlo para crear bien la base de datos y luego seguir al paso 13. Encontré esta info en https://stackoverflow.com/questions/66718132/rails-postgresql-cant-find-the-database Casi al final muestra los comandos para reiniciarlo 
sudo service postgresql stop
sudo service postgresql start
Espero te sirva :)

**Comment by Ferc28** [comment]
Hola, también me encontré con el mismo problema y llegue a esta guía:
https://rails.devcamp.com/trails/development-environments/campsites/ruby-on-rails-development-environment/guides/how-to-fix-role-does-not-exist-error-linux-postgres
GL

**Comment by AndrewVenegas** [comment]
Se pasaron! Muchas graciaaas, finalmente lo logré con el método de @Ferc28 pero igual hice el primero asi que no sé si habrá influido o no. 

Lo que hice fue:
createuser -s -r andrew_venegas
logout
rails db:create
rails server

Muchas graciaaas :D

**Comment by vice-rosas99** [comment]
hola, yo tengo el mismo error, solo que en vez de preguntarme por el usuario que cree, busca el usuario "root", saben en que parte debo editar esto para que diga el usuario que cree?
