### ISSUE TITLE
Error paso 7

### ISSUE THREAD

**Issue by ElBenJamon** [IIC2143/Setup-Guides#11]
Tengo un problema al ingresar con el usuario postgres del paso 7

![Captura](https://user-images.githubusercontent.com/101297313/224428966-9ec0982f-d408-436d-b418-2d9259acb540.PNG)

Agradezco cualquier ayuda :D.

**Comment by OrregoSilva** [comment]
Si bien dice eso, de igual forma lograste entrar a la consola de Postgresql, prueba con la creación del superusuario nomas, no creo que de problema
