### ISSUE TITLE
Error paso 2 Mac

### ISSUE THREAD

**Issue by maxvalenzuela22** [IIC2143/Setup-Guides#12]
Hola! En el paso dos al correr la ultima linea, "curl -sSL https://get.rvm.io | bash -s stable", me tira un error. He tratado de buscar soluciones en internet pero ninguna me ha resultado, hoy fui a la ayudantía y me dijieron que creara una Issue. A continuación dejo una foto del error mencionado. De antemano muchas gracias por la ayuda!
![Captura de pantalla 2023-03-10 a la(s) 18 52 03](https://user-images.githubusercontent.com/106118961/224435246-5ff994a1-30b5-4294-8492-023a28178dfe.png)

**Comment by claracuezzo** [comment]
Hola! A mí me pasó exactamente lo mismo y tampoco logré arreglarlo buscando en internet

**Comment by nbarriav** [comment]
Hola! Trataste corriendo esto?
```\curl https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable```

**Comment by claracuezzo** [comment]
Me funcionó! Gracias :)
