### ISSUE TITLE
Error paso 5 mac

### ISSUE THREAD

**Issue by mnallark** [IIC2143/Setup-Guides#14]
Hola, al ingresar 'psql postgres' en la terminal me aparece el error 'zsh: command not found: psql'. 
Como lo puedo solucionar?

<img width="564" alt="Captura de pantalla 2023-03-11 a la(s) 12 57 46" src="https://user-images.githubusercontent.com/101204719/224494519-e25c2afd-eb57-46cb-bfbe-a181f4ebd014.png">

PD: No encuentro la carpeta PostgreSQL en la libreria despues de instalarlo... quizas tenga que ver con el error.

**Comment by ncruzm** [comment]
Tenia el mismo error lo que hay que hacer es ejecutar esto `export PATH=/usr/local/opt/postgresql@9.5/bin:$PATH` y ahi debiese funcionarte

**Comment by ncruzm** [comment]
me equivoque es `export PATH=/usr/local/opt/postgresql@15/bin:$PATH`

**Comment by mnallark** [comment]
Ahora me aparece esto

<img width="567" alt="Captura de pantalla 2023-03-13 a la(s) 10 39 53" src="https://user-images.githubusercontent.com/101204719/224718773-ddc386d3-f0bc-415e-a1ac-9ed0ae7696be.png">

**Comment by SavkaAldunce** [comment]
Estoy teniendo el mismo problema y poner eso no me lo resuelve, me sigue tirando el mismo error.

**Comment by mnallark** [comment]
En la foto que subi arriba en vez de poner "psql postgres" puse "psql postgres@15" y eso me tiraba error :)
Aunque despues tampoco me resultó, tuve que borrarlo todo y empezar de nuevo porque no encontré el error.
Prueba usando la consola de Rosetta igual por si acaso.
