### ISSUE TITLE
Utilización de Ruby en windows: ¿dónde clonar el syllabus? ¿cómo editar archivos que existen en linux?

### ISSUE THREAD

**Issue by KainaBGR** [IIC2143/Setup-Guides#15]
Hola :) Estoy un poco confundida con los directorios en que debo trabajar. Resulta que mi compu tiene windows y por lo tanto seguí la Setup Guide de ubuntu. Creo que me resultó bien y puedo ejecutar archivos .rb desde la consola de ubuntu. El tema es que al no tener ruby en windows, no puedo ejecutar archivos desde vs code o la consola de windows. Entonces pensé que tendría que clonar el syllabus desde la consola de ubuntu y lo hice, pero al momento de querer editar o crear nuevos archivos en esta carpeta, me dice que es de solo lectura y no puedo. Entonces se me ocurren algunas opciones para poder trabajar en mis códigos pero no suenan tan bien o no sé hacerlas:
1. Tener mis archivos en mis carpetas de windows y así poder editarlos para luego cuando estén terminador copiarlos a carpetas de linux y ejecutarlos en ubuntu. (muy tedioso)
2. Descargar ruby en windows para así editar y ejecutar los archivos desde windows en vs code. Aunque tendría ruby 2 veces y probablemente no será cómodo cuando tenga que hacer push del proyecto, porque en esas ocasiones tendré que usar rails y, por lo tanto, ubuntu, según tengo entendido y seguiría mi duda sobre dónde guardar los archivos.
3. Tener un editor de código como vs code en linux, que me permita editar los archivos y ejecutarlos ahí mismo. Aunque no sé si es que hay alguna carpeta que sea también de edición y no sólo de lectura en linux.
Básicamente, ayuda plz no sé qué carpeta usar o dónde tener mi editor, sólo sé que cuando entro a Linux/Ubuntu tengo un montón de carpetas de nombres cortos que no tengo idea para qué sirven o cómo usarlas :(

**Comment by OrregoSilva** [comment]
Para ejecutar archivos Ruby en algún directorio de Windows (no recomendado) puedes abrir VS Code en el directorio que están tus archivos, una vez ahí, abre la terminal del editor, por default será una PowerShell, para pasar a la consola de Ubuntu basta con escribir `wsl` en ella como un comando.
