### ISSUE TITLE
Contraseña Postgres (MAC)

### ISSUE THREAD

**Issue by PabloAylwin** [IIC2143/Setup-Guides#16]
Cuando escribo el comando `psql postgres` para ingresar a la consola de Mac, me mide una contraseña que no conozco. No puedo ejecutar `CREATE USER myuser WITH SUPERUSER PASSWORD 'mypassword';`. Intenté saltarme este paso con comandos que encontré en StackOverflow ([https://stackoverflow.com/questions/46781471/why-postgresql-on-mac-asks-me-for-password-after-fresh-install]), pero al ejecutar `rails s`, el servidor dice "connection to server on socket "**/tmp/.s.PGSQL.5432" failed: fe_sendauth: no password supplied**" y creo que es porque no sé qué contraseña me pide en el paso que mencioné anteriormente y todavía no puedo prooversela. Al crear en archivo `.env`, he intentado con muchos usuarios y contraseñas distintas pero sigue sin funcionar.

**Comment by PabloAylwin** [comment]
Sigo buscando en internet y descubrí que tengo dos `superusers`: uno que se llama **postgres** y otro que creé que tiene en mismo nombre que mi usuario. Creé mi usuario usando `CREATE USER myuser WITH SUPERUSER PASSWORD 'mypassword';` pero aún no me deja entrar a la terminal de PostgreSQL desde mi usuario, solamenter desde el usuario default **postgres**. A la hora de ejecutar `rails db:create` en la carpeta de mi proyecto, me dice "**ConnectionBad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: fe_sendauth: no password supplied**", el cual es el mismo error que me da cuando intento iniciar sesión con mi usuario al ejecutar `psql postgres`.

**Comment by jtvaldivia** [comment]
Hola Pablo,  puede ser que no actualizaste la base de datos luego de crear el usuario intenta con este comando. 
 `brew postgresql-upgrade-database`
Cuentame si se arregla.

**Comment by PabloAylwin** [comment]
Al principio no me funcionaba correr ese comando, pero usé esta [referencia](https://stackoverflow.com/questions/27700596/homebrew-postgres-broken) y logré actualizar la base de datos, pero el problema sigue siendo el mismo. Al usar `rails db:create` me tira el mismo error: **Caused by:
PG::ConnectionBad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: fe_sendauth: no password supplied**. Creo que el problema es lo del superuser que no logro configurar. Antes de crear el superuser, igual me pedía la contraseña para el usuario de mi mac, y al entrar como postgres, creé un superuser con el mismo nombre, pero la contraseña no me sirve para entrar. ¿Quizá existe alguna manera de definir el usuario postgres como predetrminado? Porque como no puedo entrar vía `psql postgres`, entro utilizando `psql -U postgres` y con ese usuario sí puedo entrar con mi contraseña y puedo crear el superuser y todo lo relacionado a eso. La primera imagen soy yo intentando entrar vía
`psql postgres` y fallar tras introducir mi contraseña y la segunda es entrando vía `psql -U postgres`. El problema es que por default me pide la contraseña de PAK, pero sospecho que no es el mismo PAK que el superuser, porque es la contraseña que me pide desde un principio.
<img width="586" alt="software 1" src="https://user-images.githubusercontent.com/80900292/225469140-493a35df-8473-4ecc-88b0-92552c621bce.png">
<img width="586" alt="software 2" src="https://user-images.githubusercontent.com/80900292/225469160-68964329-3141-4694-9b73-48bc4f055669.png">

**Comment by nbarriav** [comment]
Hola, trataste borrar e instalar postgresql nuevamente? En caso que no quieras tomar esa vía, encontré algo en donde puedes hacer unos cambios en la configuración para hacerle un alter al usuario que quieras y dejarle la password en null. Esta opción la veo un poco más complicada y tampoco podría asegurarte que funcione.
Yo reinstalé postgres y no tuve ningún problema.
Dejo el [link](https://dba.stackexchange.com/questions/83164/postgresql-remove-password-requirement-for-user-postgres) (es la respuesta que tiene el 22. Ahi te redirige a otro link donde te explica como cambiar la configuración)
Saludos

**Comment by PabloAylwin** [comment]
Finalmente lo logré. De verdad muchas gracias.
