### ISSUE TITLE
Error Paso 12. Crear base de datos. 

### ISSUE THREAD

**Issue by tom4stapia** [IIC2143/Setup-Guides#19]
Hola! Al tratar de crear la base de datos me sale el siguiente error: 

![image](https://user-images.githubusercontent.com/101529711/225201984-a1eee329-cf27-492d-b781-c122369509a7.png)

No he logrado encontrar la solución en internet por si me pueden ayudar.
Muchas gracias.

**Comment by nbarriav** [comment]
Hola! 
Cambiaste el ```database.yml```del paso 11? Porque ahí se setea lo de "adapter"
