### ISSUE TITLE
Repositorio de proyecto

### ISSUE THREAD

**Issue by TMagini** [IIC2143/Setup-Guides#2]
Holaa, en la guia sale sobre los elementos que podemos pushear/subir a GitHub pero no encuentro donde estaria el repositorio al cual hacerle el push o si es el caso, como tenerlo en mi cuenta de GitHub.

**Comment by OrregoSilva** [comment]
¡Hola!
Los repositorios que les daremos estarán una vez que sean publicados los grupos, lo cual será en aprox. 2 semanas en esta misma organización.
