### ISSUE TITLE
Problemas con el setup (paso 7 y 8)

### ISSUE THREAD

**Issue by TomasAuad** [IIC2143/Setup-Guides#20]
Hola! tengo un problema en el paso 7 del set up. Tengo windows por lo que tuve que instalar wsl (lo hice viendo el video recomendado). Todo funciona perfecto hasta el paso 7. PostgreSQL: superuser.

Al poner el comando: sudo -u postgres psql

la consola me dice: could not change directory to "/home/tomi": Permission denied

Me deja seguir pero luego me da problemas para crear un nuevo proyecto con rails (paso 8).

**Comment by batemanp** [comment]
Hola, tengo el mismo problema! Si lo solucionas agradecería que me comentes como porfiss

**Comment by batemanp** [comment]
Hola, yo no podría crear un nuevo proyecto con  `rails new <nombre proyecto> --database=postgresql` , pero escribí el nombre sin `< >` y me resultó, no sé si sea el mismo error que el tuyo en el paso 8 pero para que lo pruebes :)

**Comment by TomasAuad** [comment]
Me funciono! Que grande :)
