### ISSUE TITLE
Error creación base de datos (paso 12) "role "root" does not exist

### ISSUE THREAD

**Issue by Crisiturriaga** [IIC2143/Setup-Guides#23]
![image](https://user-images.githubusercontent.com/80855714/225961763-50644e3b-47b7-4794-b0f4-add3e9cea705.png)
Holaa, al crear la base de datos me sale este error y no he podido solucionarlo, alguien que haya podido hacerlo o que me pueda ayudar??

**Comment by DiegoMillaUC** [comment]
Hola! por lo que veo, existe un error de conexión en postgresql, por lo que te recomiendo reiniciar el servicio de postgresql con el siguiente comando: 

`sudo service postgresql restart`

Luego de correrlo intenta crear la base de datos nuevamente y vuelve a comentar en esta issue para saber cómo te fue, espero que te funcione, suerte!
