### ISSUE TITLE
Error paso 7 Mac

### ISSUE THREAD

**Issue by bruverie** [IIC2143/Setup-Guides#24]
<img width="1439" alt="Captura de Pantalla 2023-03-20 a la(s) 10 44 51" src="https://user-images.githubusercontent.com/53886239/226358641-ea03f480-9695-459b-97e0-11d8132e9381.png">

Al intentar crear el proyecto me sale esto y no se crea la carpeta, pude completar todos los pasos anteriores del setup.

**Comment by bruverie** [comment]
Es M1 y cómo sé si lo hice con o sin Rosetta? o cómo. arreglo eso?

**Comment by nbarriav** [comment]
En esa consola que te tira error, que sale cuando escribes ```arch```?

**Comment by bruverie** [comment]
i386 me tira la consola al ejecutar `arch` y `arch -arm64 rails new ...` me tira el mismo error

**Comment by nbarriav** [comment]
Anda a la carpeta de Utilidades, y en la aplicación Terminal pon click derecho, clickea "Obtener información" y ve si está marcado "Abrir usando Rosetta", si es que está marcado desmarcalo y trata de ejecutar ```arch```, ahora debería aparecer arm64. Si ese es el caso, ejecuta nuevamente ```rails new ...```

**Comment by bruverie** [comment]
ahora si me sale arm64, pero me sigue saliendo el mismo problema

**Comment by nbarriav** [comment]
El problema está en la arquitectura en que fue instalado todo, probablemente haya ciertas cosas instaladas con Rosetta y otras no. La solución más fácil es instalar todo en arm64, yo lo hice de esa manera y no tuve ningún problema

**Comment by bruverie** [comment]
acabo de reinstalar todo en arm64 sin problemas y al tratar de crear el proyecto me sale el mismo problema 🥲

**Comment by nbarriav** [comment]
instalaste brew nuevamente también?

**Comment by bruverie** [comment]
no me dejó, me sale este error
`curl: (22) The requested URL returned error: 404`

**Comment by nbarriav** [comment]
Lo instalaste con el link de la página oficial o con el del repo? Trata con el que no lo hiciste

**Comment by bruverie** [comment]
logré instalar brew y reinstalé toda la guía de setup y me volvió a salir el mismo problema al tratar de crear el proyecto

**Comment by jigarciaforteza** [comment]
Pudiste crear el proyecto?? A mi me sale zsh: no such file or directory: t1software
