### ISSUE TITLE
problema mac paso 4 

### ISSUE THREAD

**Issue by Agustinuc** [IIC2143/Setup-Guides#25]
hola, al ejecutar el codigo rvm install 3.1.0, me aparece el siguiente error.
<img width="550" alt="Captura de pantalla 2023-03-20 a la(s) 23 29 55" src="https://user-images.githubusercontent.com/89665265/226505440-98da79b3-d01d-4961-8b78-d27dfda3ea2a.png">
<img width="566" alt="Captura de pantalla 2023-03-20 a la(s) 23 30 17" src="https://user-images.githubusercontent.com/89665265/226505447-5fa669ab-6c01-4c42-9562-ca28f678cd9a.png">
me pidio tambn una clave de github la cual no sabia que clave era, no se si lo que me aparecio arriba esta bien y solo tenia que poner la clave tambn..., en ese caso no se que clave me piden ya que trate con la de github y no me dejaba.
gracias

**Comment by Agustinuc** [comment]
si me corrigio el error, pero luego me salio para otro..
<img width="562" alt="Captura de pantalla 2023-03-21 a la(s) 14 56 33" src="https://user-images.githubusercontent.com/89665265/226700207-9a996095-fe03-494f-ba41-d7a293b4777a.png">
Al aparecer ese escribo brew install gcc@6 y me sale el siguiente error.
<img width="564" alt="Captura de pantalla 2023-03-21 a la(s) 14 58 57" src="https://user-images.githubusercontent.com/89665265/226700412-ab1d8001-f15f-4332-abe6-88b60e0e352a.png">

**Comment by jorgedg6** [comment]
Y si pruebas `brew install gcc`? Sin especificar la versión.

**Comment by Agustinuc** [comment]
trate y no pude. :/

**Comment by jorgedg6** [comment]
Parece un error con la versión del MacOS, ¿Puedes actualizarlo o no te deja más?

**Comment by Agustinuc** [comment]
no me deja mas

**Comment by nbarriav** [comment]
Hola, podrías ejecutar ```brew doctor``` y mostrar lo que tira? Tu computador es Intel o M1, M2?

**Comment by Agustinuc** [comment]
me tiro esto 

<img width="575" alt="Captura de pantalla 2023-03-22 a la(s) 12 08 50" src="https://user-images.githubusercontent.com/89665265/226949216-1fbef0f0-08f5-4d11-bdbd-de1b992d89f1.png">
<img width="579" alt="Captura de pantalla 2023-03-22 a la(s) 12 08 58" src="https://user-images.githubusercontent.com/89665265/226949257-44430784-f9b3-4a4c-a3e2-56e74a1a4272.png">

**Comment by nbarriav** [comment]
Son hartos warnings, creo que sale más fácil desintalar y volver a instalar brew que ir solucionando uno a uno los problemas.
Tu computador es muy antiguo?

**Comment by Agustinuc** [comment]
ya valee, como desinstalo brew? no se si tanto lo tengo desde el 2019

**Comment by nbarriav** [comment]
En este [link](https://osxdaily.com/2018/08/12/how-uninstall-homebrew-mac/) explican bien como desinstalarlo.  
Tu computador no es muy antiguo, me parece extraño  que no puedas seguir actualizándolo, te dice que está todo actualizado en tu sistema operativo?

**Comment by Agustinuc** [comment]
es del 2017 me habia equivocado, no me da la opcion de actualizarlo pero me meti a mac y me dice que mi computador se puede actualizar al sistema macOs catalina asi que lo voy a actualizar y voy a ver como me va

**Comment by nbarriav** [comment]
Buena, me cuentas como te va!

**Comment by Agustinuc** [comment]
no pude actualizarlo parece, pero borre homebrew y luego lo instale pero utilizando rbenv install 3.1.0 y me funciono no se si cambia en algo ocupar ese codigo y no el otro..

**Comment by nbarriav** [comment]
No debería haber problema si utilizaste rbenv
