### ISSUE TITLE
problema mac paso 5 

### ISSUE THREAD

**Issue by Agustinuc** [IIC2143/Setup-Guides#26]
hola, al correr el codigo psql postgres: me aparece el siguiente error.
<img width="567" alt="Captura de pantalla 2023-03-22 a la(s) 19 35 09" src="https://user-images.githubusercontent.com/89665265/227053724-5132ad2f-8e0e-4fde-a5ca-9c6a4db30438.png">

**Comment by jigarciaforteza** [comment]
Lo pudiste resolver??

**Comment by Agustinuc** [comment]
Si si pude gracias igual

**Comment by jigarciaforteza** [comment]
Cómo lo hiciste??

**Comment by Agustinuc** [comment]
Osea no pude arregarlo, tuve que pedirle el computador a mi hermano y descargar el programa en su computador. Y en el computador de mi hermano no me aparecio ese error

**Comment by jigarciaforteza** [comment]
Ok, gracias
