### ISSUE TITLE
Problema instalación Ubuntu.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Setup-Guides#27]
Estimados,

Primero traté de instalarlo con el código --wsl install a través del símbolo del sistema. Wsl dice que se instaló correctamente. Luego comienza a instalarse Ubuntu automáticamente:

Installing: Ubuntu
Ubuntu has been installed.
Lauching Ubuntu. . .
Installing, this may take a few minutes. . .
WslRegisterDristribution failed with error: 0x80370102
Please enable the Virual Machine Platform Windows feature and ensure virtualization is enable in the BIOS. 
For information please visit https: // aka.ms/enablevirtualization
Press any key to continue...

Apreto una tecla y me dice:

The installation process for distribution Ubuntu failed with exit code: 1.
Error code: Wsl/InstallDistro/WSL_E_INSTALL_PROCESS_FAILED

Y ahí termina todo. 

Por lo anterior, desistaló Ubuntu, ya que el ícono si aparece al buscarlo.

Ahora trato de instalarlo con el tutorial de youtube.

Acá seguí paso a paso y todo iba bien. Instalé el wsl a través de Windows PowerShell y salió correctamente. El problema fue nuevamente con Ubuntu, ya que fui a Store y descargué al principio la versión 22.04.5 LTS, pero al abrirlo me ejecutó error. Por lo anterior, traté con diferentes versiones, pero todas me decían lo mismo:

Installig, this may take a few minutes...
WslRegisterDistribution failed with errorL 0x80370102
Please enable the Virtual Machine Platform Windows feature an ensure virtualization is enable in the BIOS.
For information please visit https: // aka.ms/enablevirtualization
Press any key to continue...

Al apretar cualquier tecla, se me cierra el programa. 

Esto hizo buscar cual era el error 0x80370102, el cual habla sobre el Hyper - V, por lo que fuí a ''activar o desactivar las características de windows'' y activé la ''plataforma de hipervisor de windows'', luego reinicié el computador y traté de hacer las instalaciones nuevamente. Esto me dió nuevamente los mismos errores descritos. Traté de indagar un poco más pero me perdí. Es por esto que quería preguntarles que puedo hacer al respecto. 

Saludos.

**Comment by vicentethomas** [comment]
Hola! Noté que en el error te pide que te asegures que la virtualización está activada. Para ello, sigue los siguientes pasos:
1. Busca Símbolo del sistema o cmd para entrar en la consola.
2. Escribe ```systeminfo.exe``` y enter.
3. Te debería salir harta información de tu pc. En la parte de más abajo debería salir Requisitos Hyper-V. Ahí, revisa si donde sale Virtualization Enabled in Firmware (o en español) aparece como YES.

Si te aparece que no está habilitado, entonces te recomiendo buscar en particular para tu computador cómo habilitarlo a través de la BIOS. Puedes buscar: How to Enable Virtualization in BIOS <marca del computador>. Cualquier duda que tengas o si necesitas más asistencia, me preguntas nomás!

Me avisas si te funciona, saludos!
