### ISSUE TITLE
Problema con el paso 7 en MacOS

### ISSUE THREAD

**Issue by claracuezzo** [IIC2143/Setup-Guides#29]
Hola! Me sale error al correr `brew install postgresql` , pero sí logré instalar otras versiones, como postgresql@11. Como se ve en la foto, esta se instala correctamente pero después dice que no existe el comando psql. ¿Cómo lo puedo arreglar?
![Captura de Pantalla 2023-03-24 a la(s) 20 47 23](https://user-images.githubusercontent.com/89203165/227663430-e4636b59-cf6e-4d86-8d9f-c6a44595ca81.png)

**Comment by jtvaldivia** [comment]
Hola Clara, 
te recomiendo que corras los siguientes comandos:
 - `export PATH=/usr/local/opt/postgresql@11/bin:$PATH` 
 - `brew link postgresql@11 --force` 
 -  `echo 'export PATH="/usr/local/opt/postgresql@11/bin:$PATH"' >> ~/.zshrc` 
 Una de estas opciones deberia resultarte, cuentame si se resuelve o si sigues con problemas.
