### ISSUE TITLE
problema con wls.

### ISSUE THREAD

**Issue by llambias** [IIC2143/Setup-Guides#3]
luego de hacer el comando 'wsl --install' y reiniciar mi pc
revise la version con 'wsl -l -v' y obtuve 
"El Subsistema de Windows para Linux no tiene distribuciones instaladas",
"Use "wsl.exe --list --online" para enumerar las distribuciones disponibles.
y "wsl.exe --install <Distro>" para instalar."
y al hacer 'wsl.exe --install <Ubuntu-20.04>'
sigo obteniendo error "La sintaxis del comando no es correcta."
y de ahi no se como continuar.

**Comment by OrregoSilva** [comment]
Prueba instalando Ubuntu desde Microsoft Store, ahí puedes encontrar varias versiones (deje un ejemplo en la guía)
