### ISSUE TITLE
Mensaje Paso 13.

### ISSUE THREAD

**Issue by lorenzosilva** [IIC2143/Setup-Guides#30]
Estimados,

Pincho el link http://localhost:3000/ y entro a:

![image](https://user-images.githubusercontent.com/69652093/227744664-fc719ce4-6b3c-447a-8f30-b2e8357b60fa.png)
 
Y en la consola me aparece lo siguiente:

![image](https://user-images.githubusercontent.com/69652093/227744542-2c7020a2-babd-4a89-aa7b-3fc4ebe8c7fa.png)

Pero no me aparece el mensaje: 'Yay! You’re on Rails!'.

Tengo que preocuparme o igual está bien?

Saludos.

**Comment by NicolasOlmosQuiroga** [comment]
¡Hola!, esta todo bien, no es necesario que aparezca el mensaje de 'Yay! You’re on Rails!'.
