### ISSUE TITLE
Devise set up, problema al agregar el nombre

### ISSUE THREAD

**Issue by nitramavlis** [IIC2143/Setup-Guides#36]
Hola, 

tengo un problema al agregar los atributos adicionales en el setup de Device. Me funcionaba lo básico, pero al momento de agregar el nombre a los usuarios, obtengo un error por tener :name como un método no definido, en el archivo new.html.erb 

Este es el error que tengo en la consola:
ActionView::Template::Error (undefined method `name' for #<User id: nil, email: "", created_at: nil, updated_at: nil>):
    23:
    24:   <div class="field">
    25:     <%= f.label :name %><br />
    26:     <%= f.text_field :name %>
    27:   </div>
    28:
    29:   <div class="actions">

De antemano muchas gracias por cualquier recomendación que puedan darme para solucionar este problema

**Comment by catalinaortegacalderon** [comment]
a mi me sale exacto el mismo error :(
