### ISSUE TITLE
Error: 0x80370114

### ISSUE THREAD

**Issue by josefamingo** [IIC2143/Setup-Guides#40]
Hola!

Al abrir la aplicación ubuntu, me aparece el siguiente error: 
Error: 0x80370114 No se pudo iniciar la operaci¾n porque no se instal¾ una caracterÝstica requerida.

Buscando en internet, me aparecieron diferentes soluciones, pero no me funcionaron. 

Saludos!

**Comment by jean-Philipe** [comment]
El error generalmente indica que hay un problema con la instalación de WSL, verifica si lo tienes instalado correctamente antes de intentar ejecutar ubuntu, desde la PowerShell puedes intentar desinstalarlo y volver a instalarlo para confirmar una correcta instalación, si ya tenias WSL desde antes prueba a intentar actualizarlo. En algunas ocasiones un antivirus externo te puede causar problemas al instalarlo, verifica que la instalación sea correcta sin interrupciones y debería funcionar :D!

**Comment by josefamingo** [comment]
Perfecto!! lo hice y ahora el error que aparece es este: 
WslRegisterDistribution failed with error: 0x80370102
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

Pero las características de Windows están activadas. 
![Captura de pantalla 2023-08-11 164131](https://github.com/IIC2143/Setup-Guides/assets/89876553/049cfa94-3efe-4ad2-8982-ba8792997600)

¿Qué puedo hacer?

Saludos
