### ISSUE TITLE
Error Permission denied

### ISSUE THREAD

**Issue by chocolito24** [IIC2143/Setup-Guides#41]
Hola! Al tratar de  ingresar a la consola de PostgreSQL como usuario, (en el punto 7 de la guia), al correr el codigo "sudo -u postgres psql", me aparece "could not change directory to "/home/chocolito24": Permission denied"  (donde chocolito24 es mi usuario).
Como puedo solucionar esto? que no puedo seguir la instalación sin completar esta parte. Muchas gracias!

**Comment by jean-Philipe** [comment]
![image](https://github.com/IIC2143/Setup-Guides/assets/110950317/ab25a497-27b1-43c0-b029-badf1c6c02da)

No te preocupes no es un error, es un mensaje que **sale cada vez que entras** en la consola de PostgreSQL, si te fijas la ultima línea tiene un **postgres=#**, eso significa que ya estas dentro de ella, para salir solo usas **\q** y listo :D!

**Comment by chocolito24** [comment]
Buenísimo muchas gracias!!
