### ISSUE TITLE
Paso 13: Ubuntu

### ISSUE THREAD

**Issue by cristobalmujicap** [IIC2143/Setup-Guides#42]
Cree mi proyecto en psql y cree la base de datos "rails db", pero el último paso cuando corro el servidor y voy al link  http://localhost:3000/  no me aparece ningún mensaje. En consola, se imprime lo siguiente: 

Started GET "/" for ::1 at 2023-08-10 23:35:37 -0400
Processing by Rails::WelcomeController#index as HTML
  Rendering /home/cristobalmujicap/.rvm/gems/ruby-3.1.0/gems/railties-7.0.7/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /home/cristobalmujicap/.rvm/gems/ruby-3.1.0/gems/railties-7.0.7/lib/rails/templates/rails/welcome/index.html.erb (Duration: 3.5ms | Allocations: 529)
Completed 200 OK in 36ms (Views: 13.1ms | ActiveRecord: 0.0ms | Allocations: 4471)

¿Esta bien instalado, o algo anda mal?

**Comment by jean-Philipe** [comment]
Funciona perfecto, al iniciar el servidor te debería salir la siguiente imagen al entrar al link http://localhost:3000/  : 
![Captura de pantalla 2023-08-11 085749](https://github.com/IIC2143/Setup-Guides/assets/110950317/a3238c90-8807-4c3a-803d-562d6ff2415d)

Si te sale esta u otra imagen de bienvenida (depende de la versión que tengas de rails) está todo listo.

Al dar click en la imagen principal se te redirecciona a la pagina de rails, una llamada GET al link "/" la cual es procesada por el controlador WelcomeController con el metodo index y te redirecciona a los links que te muestra en consola. Como funciona esto lo verán dentro de poco en clases y entenderás lo que sale en consola, pero no te preocupes por ahora :D!

**Comment by cristobalmujicap** [comment]
Genial, gracias!
