### ISSUE TITLE
Error con el URL 

### ISSUE THREAD

**Issue by isichavezc** [IIC2143/Setup-Guides#44]
Hola! Estoy siguiendo el paso 1 (para mac), pero me dice error cuando pongo el url para instalar el Homebrew. Me aparece "The requested URL returned error: 404"

**Comment by isichavezc** [comment]
Ya lo logre instalar con otro link que encontré en internet, pero ahora en el paso número 3 me aparece el siguiente error " Warning: No available formula with the name "homebrew/core/postgresql"."

**Comment by jtvaldivia** [comment]
Hola,
Podrias subir un pantallazo con el error, para poder tener mas informacion

**Comment by isichavezc** [comment]
<img width="1440" alt="Captura de Pantalla 2023-08-16 a la(s) 11 31 04" src="https://github.com/IIC2143/Setup-Guides/assets/82611507/4727cd4d-d28f-45f7-811f-90d3889a639c">

**Comment by jtvaldivia** [comment]
Intenta especificando la version de postgresql

**Comment by isichavezc** [comment]
Supeer ahi funciono! Pero ahora me aparece un problema en el siguiente paso. 
<img width="1440" alt="Captura de Pantalla 2023-08-16 a la(s) 19 00 50" src="https://github.com/IIC2143/Setup-Guides/assets/82611507/29399aa8-452a-44fc-801d-0181d28a2e7f">
