### ISSUE TITLE
error db create

### ISSUE THREAD

**Issue by danilarco** [IIC2143/Setup-Guides#46]
Hola! Tengo un problema en el penúltimo paso en mac. Al tratar de crear la base de datos, me aparece esto:
![Captura de Pantalla 2023-08-14 a la(s) 11 46 04](https://github.com/IIC2143/Setup-Guides/assets/105876339/1b985314-dca4-47a7-b702-2f2b0f30f14a)
Al poner rails --tasks, no me aparece db:create dentro de las tareas. Ya revisé que todas las modificaciones a archivos de los pasos anteriores estén bien. Por otra parte, creo que puede tener que ver con que  postgresql no se está iniciando bien, ya que al poner brew services list me aparece lo siguiente: 
![Captura de Pantalla 2023-08-14 a la(s) 11 46 40](https://github.com/IIC2143/Setup-Guides/assets/105876339/4b7d1da7-5d4f-42fd-b29a-4833cd0de89f)

Sin embargo, puedo usar bien los comandos psql y pude crear bien el usuario, por lo que no se bien qué esta pasando. Gracias de antemano!

**Comment by jtvaldivia** [comment]
Tienes iniciado el postgres?

**Comment by danilarco** [comment]
Ya intenté varias veces borrarlo y descargarlo de nuevo pero me sigue tirando el error!

**Comment by jtvaldivia** [comment]
intenta brew services restart postgresql@14 y luego sigue los pasos del setup

**Comment by danilarco** [comment]
Lo intenté pero me sigue tirando el mismo error, y postgres no se inicia bien. Traté de instalar la versión 13 de postgresql y se inició bien, pero al poner db:create sigue tirándome el mismo error al ejecutar db:create.

**Comment by danilarco** [comment]
Aquí va application.rb: 
![Captura de Pantalla 2023-08-17 a la(s) 19 13 31](https://github.com/IIC2143/Setup-Guides/assets/105876339/5b79def5-1289-4c27-be81-fc6e7037f3d9)
De todas formas si voy mañana!
