### ISSUE TITLE
Abrir proyecto en VScode (paso 9)

### ISSUE THREAD

**Issue by chocolito24** [IIC2143/Setup-Guides#48]
Hola! Estoy con un problema para interactuar con el proyecto creado en el paso 8. Resulta que al correr el código "code ." me aparece el error adjunto en la primera imagen. 
Trate de abrir la carpeta manualmente desde VScode, pero no me deja seleccionar la carpeta de Ubuntu en la que fue creado el proyecto (adjunto 2 screenshots, uno donde estan las opciones de archivos a abrir en VScode, y otra con todos los archivos el pc donde si aparece Ubuntu).
Trate de copiar la carpeta a la sección de documentos del computador para poder abrirlo en VScode, pero no funciona para la pagina del paso 13.
Como puedo abrir la carpeta de Ubuntu desde VScode? o hay otra forma de poder trabajar el proyecto?
Muchas gracias!
![error code ](https://github.com/IIC2143/Setup-Guides/assets/110871849/4c5ed271-a6ea-4959-9f47-75081f45f150)
![abrir carpeta en VScode](https://github.com/IIC2143/Setup-Guides/assets/110871849/46998422-777e-46f2-9607-ad26277f056d)
![todos mis archivos](https://github.com/IIC2143/Setup-Guides/assets/110871849/4ac1ff53-863b-416c-8e1d-ef602d2b60a5)

**Comment by jean-Philipe** [comment]
Prueba a abrir el buscador de carpetas desde vscode, es decir, le das a archivo>abrir carpeta, luego en el buscador de arriba escribes la palabra Linux, tal como sale en la imagen (Si no lo haces así Vvcode no suele mostrar esta carpeta por default).

![image](https://github.com/IIC2143/Setup-Guides/assets/110950317/64ce854a-7245-45ce-a5bc-132bb5c1e9a6)

Si lo haces asi y le das enter, te saldrá lo siguiente:
![image](https://github.com/IIC2143/Setup-Guides/assets/110950317/db386a0a-023e-43ed-9548-1be5318d8d35)

ahí deberías poder encontrar la carpeta del proyecto :D

**Comment by chocolito24** [comment]
bacaaan muchas gracias!! ahí me resulto
