### ISSUE TITLE
Problema instalación paso 1

### ISSUE THREAD

**Issue by PabloRabeloRoa** [IIC2143/Setup-Guides#5]
Hola, estoy teniendo un error en el paso 1 para MasOs. Cuando corro `brew -v` me aparece `zsh: command not found: brew` y cuando pongo `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` me resulta `curl: (22) The requested URL returned error: 404`. No se que hacer

**Comment by OrregoSilva** [comment]
¿Has tratado de usar la consola de Rosetta? Entiendo que de los que usan Mac, usar esa via es mucho mas facil

**Comment by ManuelOvalle** [comment]
Hola, yo tengo el mismo error. Estoy abriendo la consola a través de rosetta pero me arroja lo mismo. Hay algo que se pueda hacer? Tengo actualizado el computador también.
