### ISSUE TITLE
Error con el server

### ISSUE THREAD

**Issue by gustavoaaz** [IIC2143/Setup-Guides#50]
Seguí todos los pasos de la guía de instalación, pero al verificar en el localhost me dice este error:

![image](https://github.com/IIC2143/Setup-Guides/assets/76974203/4530e365-a99f-489d-9f45-0d0e17763a10)

**Comment by jean-Philipe** [comment]
Hola!, creo que no estas iniciando el servidor de postgresql antes de intentar encender el server, para ello debes ejecutar cada vez que enciendes el computador: sudo service postgresql start desde la consola de ubuntu y ahí podrás continuar trabajando correctamente!
