### ISSUE TITLE
Error con el paso 12(rails)

### ISSUE THREAD

**Issue by pgaguilera** [IIC2143/Setup-Guides#52]
Hola. Cuando ejecuto la línea rails db:create me indica lo siguiente

![Captura de pantalla (1)](https://github.com/IIC2143/Setup-Guides/assets/111088814/1e6d4dbb-4125-4f7d-ac69-d24332afce65)

Después intento hacer lo que me pide con el comando rails ~new/Code/Ruby/weblog y aun así después no funciona. No sé qué hacer :(.

![Captura de pantalla (2)](https://github.com/IIC2143/Setup-Guides/assets/111088814/ff620963-6be4-4edc-a170-37d0ff8c8f87)

**Comment by ignacio-sp** [comment]
Hola!, por lo que veo en la primera imagen no estas corriendo `rails db:create` dentro de la carpeta del proyecto, escribe `cd <nombre_proyecto>` y una vez dentro del directorio intenta correr nuevamente `rails db:create`. Cuéntame cómo te va!
