### ISSUE TITLE
Error paso 4 mac

### ISSUE THREAD

**Issue by FranciscoOrtuzar** [IIC2143/Setup-Guides#53]
Hola, he tenido infinitos problemas instalando rails, y ahora me surgió otro error.
Me dice que no se pudo compilar un archivo
<img width="771" alt="Captura de Pantalla 2023-08-21 a la(s) 19 20 46" src="https://github.com/IIC2143/Setup-Guides/assets/101532996/f5432358-c9b1-43b6-8789-4f5dee3d15c2">
No sé como arreglarlo

**Comment by jpsandoval** [comment]
hola, ya vi ese error con anterioridad pasa a vedces con las maquinas M1 o M2. Par solucionarlo hay que agregar unos parametros de openssl al comando que instala rails, algo como:

rvm install ruby-3.2.2 --with-openssl-dir=/opt/homebrew/opt/openssl@1.1

si buscas en internet encontraras mas ejemplos, sino puedes venir a clase, y al final te ayudo
