### ISSUE TITLE
Error paso 8 - creando psql

### ISSUE THREAD

**Issue by tariztia** [IIC2143/Setup-Guides#54]
Hola! no se por que no puedo crear un proyecto de psql

![image](https://github.com/IIC2143/Setup-Guides/assets/105675471/cdabf1c2-6535-4e2a-a0d5-445a76d0d3c9)

**Comment by ignacio-sp** [comment]
Hola! Debes escribir el nombre del proyecto sin los `<>`, en este caso como `proyecto_prueba`, es importante también que no tenga espacios para que tome el nombre completo. Espero te sirva!
