### ISSUE TITLE
Error server paso 13

### ISSUE THREAD

**Issue by tariztia** [IIC2143/Setup-Guides#55]
Hola! al entrar al servidor me aparece esto:
![image](https://github.com/IIC2143/Setup-Guides/assets/105675471/ae501f37-46a5-4bd8-8b7f-514d943e7dad)

**Comment by jpsandoval** [comment]
eso suele pasar porque postgresql no esta corriendo y escuchando consultas en el puerto que menciona. A veces cuando recinicias el computador postgresql se detiene. Para iniciar postgresql debes ejecutar este comando:

brew services start postgresql
