### ISSUE TITLE
Duda wsl - ubuntu: permitir subsistema windows para linux

### ISSUE THREAD

**Issue by santiago3c** [IIC2143/Setup-Guides#58]
Hola, mi situación es que en el semestre pasado instalé wsl y ubuntu en un programación avanzada, pero no se si lo hice bien, entonces fue revisando el tutorial y vi que no tenía pinchada la casilla subsistema de windows para linux. No se si debería pincharla:
![Captura de pantalla (280)](https://github.com/IIC2143/Setup-Guides/assets/142272696/993f0d38-f713-49c2-a8ab-2e86f34e68ba)

Porque para ver si está bien instalado, pongo wsl --status y no me sale bien:
![Captura de pantalla (278)](https://github.com/IIC2143/Setup-Guides/assets/142272696/6f6d3d65-eaf6-49ff-98a6-8eb97e0431f6)

Pongo un par de comandos de ubuntu para ver si está bien:
![Captura de pantalla (279)](https://github.com/IIC2143/Setup-Guides/assets/142272696/96c827eb-0062-4103-91cc-c1e2759290b3)

**Comment by FelipeMunozMoraga** [comment]
Hola! 
Selecciona la casilla subsistema de windows para linux y luego intenta continuar con el tutorial, eso debería permitir el buen funcionamiento de wsl. 
No entendí el pantallazo de Ubuntu, solo se ve como pasaste de root a home (al hacer cd ..), pero no me queda claro que problema se ve reflejado en eso
Cualquier consulta o duda relacionada por favor no dudes en responder para seguir ayudándote!

**Comment by santiago3c** [comment]
dale gracias, ahí lo instalé
