### ISSUE TITLE
Error de permisos al instalar Rails

### ISSUE THREAD

**Issue by crisasm01** [IIC2143/Setup-Guides#6]
Hola!

Siguiendo la guía de instalación para Ubuntu, tengo un problema al llegar a Rails (paso 5). Pude instalar RVM sin problemas, pero al intentar instalar Rails me aparece el siguiente mensaje:

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/3.0.0 directory.
```

Qué debo hacer para poder obtener los permisos? No creo que sea muy seguro usar `sudo`. Probé otras soluciones que encontré en internet y no funcionó.

Saludos!

**Comment by OrregoSilva** [comment]
¿Estás realizando la instalación de los programas en la carpeta _root_ de tu computador? Si no es así, puedes llegar ahí fácilmente con el comando `cd ~`

**Comment by crisasm01** [comment]
Sí, me aseguré de realizar la instalación en _root_. Aún así, lo intenté otra vez luego de ejecutar `cd ~` y sigo teniendo el mismo problema.

**Comment by crisasm01** [comment]
UPDATE: Tras pasar largo tiempo investigando, logré encontrar la solución para instalar Rails y no usar `sudo` en el intento.

Lo primero que hice fue dirigirme al directorio `/var/lib` y luego escribir en la terminal

`sudo chmod -R a+w gems/`

Luego, volví al directorio raíz (con `cd ~`) y modifiqué el archivo `.bashrc`, añadiendo las siguientes líneas:
```
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
```
Finalmente, reinicié la terminal e instalé Rails escribiendo

`gem install rails -v 7.0.4 --user-install` (Es necesario añadir la _flag_ para que se instale)

Con eso logré instalar Rails y puedo crear un proyecto sin problemas.
