### ISSUE TITLE
Error instalando pg 1.5.6: An error occurred while installing pg

### ISSUE THREAD

**Issue by F0326** [IIC2143/Setup-Guides#60]
Hola, tengo un error al ejecutar`bundle install` en la carpeta del proyecto:
![image](https://github.com/IIC2143/Setup-Guides/assets/142538329/c04cf340-bb65-47d8-9ff0-dac911c53605)

Al pasarlo a vscode me aparece esto en la versión de pg:
![image](https://github.com/IIC2143/Setup-Guides/assets/142538329/7863585e-91dd-429b-acff-9b73225be574)

**Comment by meretamal** [comment]
Hola 😁 , antes de correr `bundle install`, instalaste postgres con los comandos que salen an la guía de setup?
