### ISSUE TITLE
Error Paso 12. root does not exist

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2143/Setup-Guides#61]
estoy teniendo problemas as intentar el paso 12 (ver captura de pantalla). Intenté reiniciando el servidor de postgres pero no funciona, tambien intenté los pasos de la issue: Error creación Base de Datos (pasos 12-13) con la guía: https://rails.devcamp.com/trails/development-environments/campsites/ruby-on-rails-development-environment/guides/how-to-fix-role-does-not-exist-error-linux-postgres , pero me no me está aceptando las claves del superusuario.
![Captura de pantalla 2024-03-08 130904](https://github.com/IIC2143/Setup-Guides/assets/62083572/62b26057-470e-482e-a75b-0bad74f71d4e)

**Comment by MatiLaB** [comment]
Yo también tenía el mismo problema. Intenté con la la guía que mandaste y me funcionó, pero a mi no me pidió la clave del super usuario, no la necesitaba ingresar. Revisa que este poniendo la misma clave que creaste en uno de los pasos anteriores. 
Perdón por no saber como ayudarte más en tu problema, pero gracias por la guía :]

**Comment by vice-rosas99** [comment]
hola, otra cosa que hay que mencionar es que el programa está buscando el role root, pero el usuario que cree en pasos anteriores es Vice, jamás cree un usuario con el nombre root. Tal vez la solución sea buscar desde donde está sacando el rol "root" (escrito en algún archivo del proyecto) y cambiarlo, pero hasta ahora no encuentro ningun archivo con "root"

**Comment by vice-rosas99** [comment]
pude resolverlo, hay que crear un usuario postgre llamado "root", pasos
en la consola de ubuntu:
->sudo su
->sudo su - postgres
->createuser -s -r root
luego: ctrl + d
y volver a intentar el paso 12 de la guía
