### ISSUE TITLE
Error en instalación de rails MacOS (M1): Rails is not currently installed

### ISSUE THREAD

**Issue by AndreaPGS** [IIC2143/Setup-Guides#63]
Hola, tengo el siguiente problema con la instalación de rails:
<img width="658" alt="Captura de pantalla 2024-03-10 a la(s) 10 19 22" src="https://github.com/IIC2143/Setup-Guides/assets/127260126/0914d404-ed0c-449f-bdad-37e1d537664e">
Todos los pasos anteriores funcionan, pero a la hora de usar el rails dice que no está instalado (pero si se encuentra en el computador). 
Al usar el comando que sugieren sigue ocurriendo lo mismo:
<img width="629" alt="image" src="https://github.com/IIC2143/Setup-Guides/assets/127260126/f90e351f-67b7-48c4-93d6-00b7d1dbd50f">

**Comment by jtvaldivia** [comment]
intenta ocupando gem install rails.

**Comment by meretamal** [comment]
Hola 😁 , puedes intentar instalar `railties 7.0.4`? Esa gema maneja el cli de rails

**Comment by AndreaPGS** [comment]
Sigo con el mismo problema inicial, y al intentar instalar `railties 7.0.4` no encuentra una versión válida, así que instalé la más alta que pude (7.1.3.2) y el problema persiste.
