### ISSUE TITLE
Paso 8. -bash: nombre: No such file or directory

### ISSUE THREAD

**Issue by valediazd** [IIC2143/Setup-Guides#64]
hola, ya hice todos los pasos anteriores y llegué a el paso 8, en el que copié y pegué el código que salía en el setup:
rails new <nombre proyecto> --database=postgresql
pero me sale que no existe el directorio... que debo hacer?
gracias!

**Comment by FelipeMunozMoraga** [comment]
Hola! En el codigo que pusiste falta el nombre de tu proyecto, debe ser algo del estilo:
rails new nombre_proyecto --database=postgresql
Espero eso solucione tu problema! Cualquier cosa por aquí mismo puedes consultar 😄
