### ISSUE TITLE
Crear múltiples proyectos

### ISSUE THREAD

**Issue by santiago3c** [IIC2143/Setup-Guides#68]
Una pregunta, ¿puedo crear todos los proyectos que yo quiera siguiendo los pasos desde el paso 8 en ubuntu, es decir, si quiero probar cosas, puedo crear la cantidad de  proyectos que yo quiera siguiendo esos pasos, y luego los puedo eliminar?

**Comment by jtvaldivia** [comment]
Sip, pero tienes que tener ojo con las bases de datos que se van a ir creando(si no vas a ocuparla eliminarla).

**Comment by santiago3c** [comment]
gracias
