### ISSUE TITLE
Error en paso 7: could not change directory to "*": Permission denied

### ISSUE THREAD

**Issue by valediazd** [IIC2143/Setup-Guides#69]
hola, cada vez que corro "sudo -u postgres psql" me sale el siguiente error: could not change directory to "/home/valentina": Permission denied
psql (14.11 (Ubuntu 14.11-0ubuntu0.22.04.1))
Intenté arreglarlo, pero si cambio directorios o doy ciertos permisos (que según internet pueden servir), me da errores después para usar la consola en general... dejo una imagen de lo que me aparece...
gracias

![image](https://github.com/IIC2143/Setup-Guides/assets/101536583/140ec63c-bf08-4b95-b328-1c7f7849bc36)

**Comment by meretamal** [comment]
Hola 😁, viendo tu consola, si se logra conectar a postgres. Al intentar crear el usuario te funciona?
