### ISSUE TITLE
Error paso 2: No route to host

### ISSUE THREAD

**Issue by FranCaprile** [IIC2143/Setup-Guides#70]
Hola! Al ejecutar 'gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB' tengo el siguiente error: 'gpg: recepción del servidor de claves fallida: No route to host'.

Seguí lo que respondieron en una issue anterior (https://github.com/IIC2143-2021-1/Syllabus/issues/7) pero no me funciona. Tengo mac intel.

Gracias!

**Comment by jtvaldivia** [comment]
Hola, 
intenta con el siguiente codigo 
gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

Si no puedes entrar a la pagina de documentacion de RVM y te daran distintas opciones de servidores alternativos
