### ISSUE TITLE
Problemas con Computador y SVM

### ISSUE THREAD

**Issue by ExRage2000** [IIC2143/Setup-Guides#71]
Hola, estoy teniendo dificultades para las instalaciones en mi computadora, en particular la parte referida a activar el **subsistema de Linux y la maquina virtual** para instalar Ubuntu:

Todo empezó el viernes en la ayudantía cuando intenté instalar ubuntu y el computador me decía que la maquina virtual estaba desactivada, el ayudante me dijo que viera un tutorial y en ese me decía que tenía que activarla en el BIOS, lo hice tal como decía y mi computador dejo de encender como corresponde (aparecía algo como "intentando reparar" y fallaba). 
El lunes entonces lo llevé a reparar y tuvieron que formatearlo porque no había forma de que encendiera.
Luego, ese mismo día decidí seguir paso a paso el [Tutorial de Youtube](https://www.youtube.com/watch?v=n-J9438Mv-s) que aparece en el github "Setup-Guides" de este mismo curso:
![Anotación 2024-03-13 101049](https://github.com/IIC2143/Setup-Guides/assets/69613733/c7a5bb8f-dd22-4502-ab18-621640747d3a)

Desafortunadamente, tras llegar a la parte donde debía activar el subsistema de Linux y la maquina virtual en características de Windows y reiniciar, ocurrió nuevamente que el computador no iniciaba y ayer tuve que llevarlo nuevamente a formatear.

Debido a esto, estoy intentado conseguir un nuevo computador para usarlo solo en este curso, pero hasta entonces necesito alguna **pagina, aplicación o software** que me permita realizar las tareas para no atrasarme. Durante la clase del lunes también hable con la profesora y la ayudante de bienestar de mi situación y me sugirieron usar _Replit_ por el momento para las clases, aunque dijeron que esto no bastaría para las tareas, por lo que me comentaron la posibilidad de **conseguir un computador del DCC** (también me dijeron que escribiera esta issue).

Lo ideal para mi sería poder instalar Ruby (o Ubuntu) en este computador por un **medio alternativo a WSL**, ya que he perdido  suficientes recursos (tiempo y dinero) intentado hacerlo funcionar de la forma "oficial" y no quiero tener que formatear mi computador nuevamente, pero si existe una forma de trabajar en las tareas en algún **ambiente online**, también me serviría.

Gracias por su atención.
Rodrigo Elsdale

**Comment by GSegov1a** [comment]
Hola, espero que lo hayas podido solucionar,
en caso de que no, te explico como lo solucione yo (tengo un asus).

Accede a la BIOS
Entra a opciones avanzadas
Activa "SVM mode"
Cambia "UMA Frame buffer size" a "Auto"
Guardas y sales

Espero te funcione :)

**Comment by ExRage2000** [comment]
Hola
Lo que pasa es que literalmente ya no quiero volver a meterme a BIOS o características de windows porque no hay garantías de que “no tenga que formatear nada” (si lo que probé tampoco debió estropear mi computador), y si falla ahora perdería el fin de semana completo antes poder llevarlo a reparar (y no es gratis)

Por eso lo que estoy buscando son alternativas mientras intento conseguir un sistema que funcione.

**Comment by GSegov1a** [comment]
No se como fue tu problema pero en mi caso, activaba el SVM en la bios y al iniciar se quedaba en negro y me mandaba a la reparación de Windows que no hacía nada, si desactivaba el SVM volvía a funcionar.

Y como te decía, si además de activar el SVM pones el UMA frame buffer size en auto se soluciona, o por lo menos en mi caso.

Pero bueno, te dejo el datito, suerte :)
