### ISSUE TITLE
Error en paso 12: rol "*" does not exist

### ISSUE THREAD

**Issue by GSegov1a** [IIC2143/Setup-Guides#72]
Hola, tengo un problema al momento de ejecutar el comando proporcionado.
Adjunto pantallazo del error
![image](https://github.com/IIC2143/Setup-Guides/assets/127225618/4c28e628-e9cf-4f90-bd43-a024ed0c052c)
Muchas gracias de antemano.

**Comment by AAromero1** [comment]
Hola, al parecer tuviste un problema con la creacion del role con el super usuario, te recomiendo volver a utilizar estos comandos 
sudo service postgresql start
sudo -u postgres psql
y cuando te aparesca la consola de psql, utiliza
\du
y revisas que el nombre sea el mismo que colocaste en el archivo .env  . Cualquier cosa responde esta issue para seguir ayudandote ;)

**Comment by GSegov1a** [comment]
Puse el comando y me entrego esto
![image](https://github.com/IIC2143/Setup-Guides/assets/127225618/53fbb3a7-9cc5-4154-9185-2a2a9d68ce99)

y el archivo .env esta asi
![image](https://github.com/IIC2143/Setup-Guides/assets/127225618/702ee70d-bea6-4259-8bfe-e1b82c30fbe8)

pero sigue dando el mismo error.
![image](https://github.com/IIC2143/Setup-Guides/assets/127225618/cb5cbc8c-bd40-4f8e-ac4f-4ebafd5f4128)

**Comment by AAromero1** [comment]
Hola, lamento la demora, pero ya encontre como arreglar ese problema. Crea un rol de super usuario con el paso 7 y de nombre le colocas el mismo usuario que tengas en el computador, este caso gsegovia. De ahi sigues los demas pasos y todo deberia ir super.

**Comment by GSegov1a** [comment]
Muchas gracias, con eso si funciono.
