### ISSUE TITLE
Tarea

### ISSUE THREAD

**Issue by blampasona18** [IIC2143/Setup-Guides#78]
Hola necesito ayuda para conectar el repositorio que nos dieron para entregar la tarea con mi proyecto local SoccerApi (en ubuntu de Windows)
Usé ssh (creé una ssh key) e hice git clone <link> dentro de SoccerApi.
Me salió el siguiente error al intentar hacer commit 
![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/f92640e7-9ef1-408c-8cf7-a190267e087c)

y este cuando intento hacer push
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Agradezco cualquier ayuda por favor

**Comment by jtvaldivia** [comment]
Podrias mandar una foto de como se ve tu repositorio desde fuera y la consola

**Comment by blampasona18** [comment]
No sé si te entiendo bien, borré la app de SoccerApi para hacerlo todo de nuevo, el tema es que no me encuentra el repositorio

**Comment by jtvaldivia** [comment]
pero lo tienes clonado?
si lo tienes clonado estas en la carpeta del repo cuando quieres pushear

**Comment by blampasona18** [comment]
ahora ya no, pq cuando creé el proyecto SoccerApi, hice git clone ahí dentro y me salió el error que puse arriba. Entonces borré el proyecto. Estuve harto rato intentando solucionarlo con chatgpt y videos de yt pero no me funciona y no sé por qué

**Comment by jtvaldivia** [comment]
clona el repo en tu escritorio y ahi mueve los archivos al repo

**Comment by blampasona18** [comment]
pero entonces tendré que mover los archivos cada vez que quiera pushear? pq como es windows, las carpetas que yo abro en ubuntu las abro directo desde la terminal, no existen si las quiero ver desde afuera

**Comment by jtvaldivia** [comment]
puedes mandarme una foto de como se ve tu repositorio en el terminal?

**Comment by blampasona18** [comment]
![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/2cb5a906-092c-495f-b1ed-fc863c98b45f)
 
Me sale esto si intento clonarlo desde la terminal normal (en una carpeta en mi escritorio)

**Comment by jtvaldivia** [comment]
Y si intentas con https y no con ssh?

**Comment by blampasona18** [comment]
mi idea era no hacerlo con https porque leí que al clonar con https te pide tus datos de github cada vez que haces commit, en cambio con ssh (como lo hice en avanzada) no

**Comment by blampasona18** [comment]
lo hice con https nomás, pero ahora mi duda es como usar la terminal de ubuntu para correr esos archivos (tiene una raíz distinta)

**Comment by CristobalPerez-Cotapos** [comment]
Hola @blampasona18!!

Mira, lo más fácil es abrir el explorador de archivos en Ubuntu y mover los archivos de tu proyecto dentro del repositorio, los pasos que tendrías que hacer son los siguientes:

-> Clona nuevamente el repositorio que te dimos nosotros en el origen de la consola de Ubuntu (o en otra carpeta si quieres un orden personalizado)
-> Sin entrar a la capeta, escribe el comando "explorer.exe ." (ojo con el espacio y el punto al final, son importante)
-> Mueve los archivos de tu tarea al reositorio usando el explorador de archivos
-> Corre los comandos de set-up de la base de datos para tenerla conigurada en esta nueva ubicación
-> Prueba que tu tarea funcione
-> Haz commit y push como los harías normalemnte, debería funcionar bien. 

Avisame si te resulta!! 😄

**Comment by blampasona18** [comment]
Hola! Me salen 2 errores, el primero con el push no me lo está reconociendo
![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/0e44f235-9302-443b-a480-da2b9b3d6799)

El segundo es con la base de datos, como había creado antes el proyecto, al parecer al eliminarlo no se eliminó la base de datos
![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/cb4b2dda-41c1-4ef5-b3db-7d0ce86e590f)

**Comment by CristobalPerez-Cotapos** [comment]
Hola!! 

1. Respecto al push, no te resulta ya que estás pusheando desde el directorio incorrecto, (ya que el repo estpa en "2024-1-Tarea..." y tu estas pusheando desde SoccerApi)
2. Mientras la tarea corra, no es grave que estés con la base de datos anterior, por lo que eso no debería ser un problema. 

Cuentame si te funcina!! 😄

**Comment by blampasona18** [comment]
1. Hice el push y se subió pero en github no sale nada, me podrías confirmar si se ve?
2. ok pero esq mi carpeta /db no tiene el archivo schema.rb (es como si no tuviera base de datos). Mi proyecto se puede llamar SoccerApi1? o el nombre es estrictamente necesario

**Comment by CristobalPerez-Cotapos** [comment]
Me aparece un push, pero ain los archivos dentro, solo me dice que creaste un sub-modulo. 

Te aseguraste de hacer el git add y commit correctamente?

mandame pantllazos para ver que no diga nada extraño.

**Comment by blampasona18** [comment]
Me salió eso

![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/de9f0abd-4d6f-463b-8c04-4be5ebdd27a5)

**Comment by CristobalPerez-Cotapos** [comment]
Como indica el mensaje en el add, soccerApi también es un repositorio, y eso causa el error.

Para solucionarlo, ejecutando rm -rf .git dentro de la carpeta SoccerApi, y volciendo a hacer add, commit y push

Avisame si te funciona 😄

**Comment by blampasona18** [comment]
No me funciona :// De verdad sorry por molestar tanto pero no me manejo con ubuntu y me enredó el tema, ni idea ahora qué podría fallar, me sale como que está al día 

![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/178a00fe-4cc5-4d8a-b29f-e4e49d45df1a)

**Comment by blampasona18** [comment]
Puede haber algun problema si hice git clone del repo en otra carpeta? pq en algun momento para intentar solucionarlo, cloné el repo con la terminal normal (abriendola desde el explorador de archivos de mi carpeta de software que tengo en el escritorio)

**Comment by CristobalPerez-Cotapos** [comment]
Tranquilo Bruno!! esto vamos a sacarlo!!
No hay problema con tener varios clones, de echo así es como se trabaha en los repos 

Lo que me imagino que pasó ahora es que se te marcó SoccerApi como un módulo, y por eso no se pushea, una opción es volver a clonar tu respositorio y ahcer lo siguiente:

-> Volver a clonar tu repostorio en Ubuntu
-> Borrar el módulo que aparezca ahí
-> Volver a colocar SoccerApi
-> asegurarse de correr el comando para que no se lea como repositorio
-> push

Comentame si te resulta, pero tranquilo que alguna solución vamos a encontrar 😉

**Comment by blampasona18** [comment]
Cual sería el comando para que no se lea como repositorio? o solo volver y no hacer el commit desde SoccerApi
Gracias !

**Comment by CristobalPerez-Cotapos** [comment]
rm -rf .git

**Comment by blampasona18** [comment]
Me sale lo mismo que antes, no se actualiza nada :(

![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/d753853d-3653-4110-a807-0d21053a285d)

Luego lo eliminé e intenté clonarlo con https y me tiró esto, leí lo que dice sobre los tokens y lo creé pero no me da la opción de activarlo, ya que me sale que no tengo la autenticación:

![image](https://github.com/IIC2143/Setup-Guides/assets/114322883/439833fd-97ad-4003-b92b-b1419d9796cd)
