### ISSUE TITLE
Error de instalación paso 2: command not found gpg

### ISSUE THREAD

**Issue by mt-garcia** [IIC2143/Setup-Guides#8]
Hola! Al hacer el segundo paso de instalación, se logran ejecutar unas cosas pero otras no, dándome este resultado:
<img width="897" alt="Captura de Pantalla 2023-03-09 a la(s) 10 26 23" src="https://user-images.githubusercontent.com/69651156/224036972-13a0ae22-50b2-412d-82d4-36de342d9462.png">

**Comment by OrregoSilva** [comment]
Es posible que esté fallando porque colocaste 3 comandos al mismo tiempo, si no, ¿trataste con el comando que te sugiere la consola `xcode-select --install`?
