### ISSUE TITLE
Error paso 13

### ISSUE THREAD

**Issue by MaxAl100** [IIC2143/Setup-Guides#9]
Estuve siguiendo el tutorial para windows y me sirvió todo hasta el paso 13, pero al abrir la página me sale lo siguiente.

![imagen](https://user-images.githubusercontent.com/43099597/224358910-d7b80a60-14f1-47ed-8cc8-4873c075a8fe.png)

Pregunté en la ayudantía y me dijeron que creara un issue del problema.

Agradezco cualquier ayuda.

**Comment by KainaBGR** [comment]
Hola, a mi también me pasó lo mismo y en la consola salía "ConnectionBad: could not connect to server: No such file or directory". Entonces llegué a esta página https://stackoverflow.com/questions/66718132/rails-postgresql-cant-find-the-database y chequié el servidor como dice casi al final 
sudo service postgresql status 
y me arrojó que estaba down. Entonces lo reinicié como dice 
sudo service postgresql stop
sudo service postgresql start
y con eso hecho intenté crear la base de datos de nuevo con 
rails db:create
ahí sí se creo la base (no como antes) y luego pude correr el servidor del paso 13. Espero te sirva :)

**Comment by MaxAl100** [comment]
Muchas gracias, eso resolvió el problema! 😄
