### ISSUE TITLE
permission denied en ubuntu con mi usuario

### ISSUE THREAD

**Issue by DikinBausCompletos** [IIC2143/Setup-Guides#93]
hola, estoy teniendo problemas para acceder a las carpetas en ubuntu, me aparece el mensaje de que no tengo permiso de administrador, pero no tengo otro usuario en mi compu, intente dar permiso para leer y cambiar la carpeta pero no me da permiso con el usuario actual, esto tambien pasa con la carpeta home, ejecutar como administrador tampoco soluciona nada, ¿hay aguna forma de cambiar usuario y/o darle administrador al usuario actual?
nisiquiera puedo acceder desde el buscardor de archivos ni visual
![Captura de pantalla 2024-08-21 165130](https://github.com/user-attachments/assets/1d590d50-dcb5-47c2-b1c3-7797d4a7b0a6)
![Captura de pantalla 2024-08-21 164946](https://github.com/user-attachments/assets/de726687-3541-45b5-adc9-86d0c83c5fb4)
![Captura de pantalla 2024-08-21 164902](https://github.com/user-attachments/assets/92d020af-400e-4d93-b703-bdcd19da8701)

**Comment by Julius9** [comment]
Hola! el problema parece radicar en los permisos de WSL para entrar a la carpeta root, esta carpeta esta reservada para el usuario administrador, por lo que no puede accederse con un usuario normal. Una solución (para la powershell) podría ser utilizar el siguiente comando:

1. `sudo -su`

Este comando inicia una terminal con los permisos de un usuario administrador, posteriormente a esto puedes ejecutar

2. `cd /root`

Finalmente, te sugeriría mucho más utilizar la consola de ubuntu que recomienda el curso (en la guia de instalación es esta: https://apps.microsoft.com/detail/9n6svws3rx71?hl=en-us&gl=US). Ya que al abrir esta consola de Ubuntu, se accede automaticamente a la carpeta `/root` y con esto puedes evitarte cualquier problema de permisos con windows

**Comment by DikinBausCompletos** [comment]
muchas gracias!
